version: '3'

services:
  docs:
    image: mak_project_local_docs
    container_name: mak_project_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./mak_project:/app/mak_project:z
    ports:
      - '9000:9000'
    command: /start-docs
